POST https://51jishu.com/userinfo/user/loginByAppKey HTTP/1.1
 Content-Type: application/json

{ 
    "app_key":"7c1373b8fec010dba9b2cf06e7b232a7",
    "app_secret":"fec010dba9b2cf06"
}

###
POST https://51jishu.com/api/open/achievement/submit HTTP/1.1
 Content-Type: application/json
 Authorization: user-center:eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjE4OTM5LCJzdGEiOjE3MDAwMDI3MjgzMzcsIm1vYmlsZSI6IjE1MzgxMDM2NzEyIiwiZHR5cGUiOiJBUEkiLCJleHAiOjE3MDAwODkxMjgzMzcsImVtYWlsIjpudWxsfQ.IXsZHjHj0u0smeQUJjy9biMmehjfRkJxUn3fC9eSd14

 {"patent":1,"transfer_mode":["apply_transfer"],"maturity":"development","invoice_no":"CGZH20220417000094","is_back":true,"classification":["6","6001"],"patent_detail":[{"owner":"向俊","effective":1,"asset_no":"2L202011077580.6","inventor":["前傻","姚宗贾"],"patent_name":"一种基于图神经网络强化学习的机器人自主控制方法","patent_no":"CN202011077580.6"}],"pricing_type":"definite","detail_url_cn":"凌凌切切","public":1,"affiliating_area":["0","330000","330101"],"permit_period":"","price":{"amount":20},"contact":"网网","principal_type":["enterprise"],"name_cn":"一种基于图神经网络强化学习的机器人自主控制方法"}