export const dataSource = [
  {
    key: 'caption',
    caption: '浙江省财政厅',
    marketId: '123455wqwr234c',
    typeName: '浙江省财政厅',
    sellAuth: 'zjsczt',
    jianjie: 'zjsczt',
  },
  {
    key: 'caption1',
    caption: '测试2',
    marketId: '黄家驹',
    typeName: '黄',
    sellAuth: '14567364435',
    jianjie: 'zjsczt',
  },
  {
    key: 'caption1',
    caption: '测试2',
    marketId: '黄家驹',
    typeName: '黄',
    sellAuth: '14567364435',
    jianjie: 'zjsczt',
  },
  {
    key: 'caption1',
    caption: '测试2',
    marketId: '黄家驹',
    typeName: '黄',
    sellAuth: '14567364435',
    jianjie: 'zjsczt',
  },
  {
    key: 'caption1',
    caption: '测试2',
    marketId: '黄家驹',
    typeName: '黄',
    sellAuth: '14567364435',
    jianjie: 'zjsczt',
  },
  {
    key: 'caption1',
    caption: '测试2',
    marketId: '黄家驹',
    typeName: '黄',
    sellAuth: '14567364435',
    jianjie: 'zjsczt',
  },
  {
    key: 'caption1',
    caption: '测试2',
    marketId: '黄家驹',
    typeName: '黄',
    sellAuth: '14567364435',
    jianjie: 'zjsczt',
  },
];
