/** 分组菜单类型 */
export enum GroupMenuType {
  'User' = '个人',
  'Team' = '组织',
  'Agency' = '机构',
  'Cohort' = '群组',
  'Company' = '单位',
  'Station' = '岗位',
  'Property' = '属性',
  'Dict' = '字典',
  'Species' = '分类',
  'Authority' = '权限',
  'OutAgency' = '外部机构',
  'Friends' = '我的好友',
  'UserCohort' = '我的群组',
  'InnerAgency' = '内部机构',
  'StationSetting' = '岗位设置',
  'CompanyCohort' = '单位群组',
  'ResouceSetting' = '资源设置',
  'Template' = '业务设置',
  'PageDesignList' = '门户页面',
  'PageCompList' = '门户组件',
}
