#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit $1


# #!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# # Export Git hook params
# export GIT_PARAMS=$*

# npx --no-install fabric verify-commit
